import {
  AudioLines,
  BookA,
  BookOpen,
  BookOpenText,
  BookUp2,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleUserRound,
  Command,
  Copy,
  FileText,
  FolderKanban,
  GraduationCap,
  Headphones,
  History,
  LayoutGrid,
  LibraryBig,
  Loader2,
  LogOut,
  NotebookPen,
  PanelLeftClose,
  PanelLeftOpen,
  Pen,
  Settings,
  Slash,
  Speech,
  Star,
  Users,
} from "lucide-react";

export const Icons = {
  Learn: BookOpenText,
  Levels: BookUp2,
  Vocabulary: BookA,
  Practice: NotebookPen,
  Reading: BookOpen,
  Listening: Headphones,
  Writing: Pen,
  Speaking: Speech,
  Pronunciation: AudioLines,
  Exams: GraduationCap,
  SignOut: LogOut,
  Books: LibraryBig,
  Profile: CircleUserRound,
  PanelLeftOpen,
  PanelLeftClose,
  Slash,
  Copy,
  Check,
  Loader: Loader2,
  ChevronRight,
  ChevronLeft,
  Command,
  FileText,
  FolderKanban,
  History,
  LayoutGrid,
  Settings,
  Star,
  Users,
};
