import {
  CalendarIcon,
  ChevronLeft,
  ChevronRight,
  CirclePlus,
  CircleUserRound,
  Droplet,
  HouseIcon,
  LayoutGrid,
  List,
  LogOut,
  MapPin,
  MoreHorizontal,
  UserCog,
} from "lucide-react";

export const Icons = {
  Profile: CircleUserRound,
  Settings: UserCog,
  WaterMeter: HouseIcon,
  WaterMeters: LayoutGrid,
  MeterReadings: List,
  SignOut: LogOut,
  ChevronRight,
  ChevronLeft,
  Add: CirclePlus,
  Logout: LogOut,
  Calendar: CalendarIcon,
  MoreHorizontal,
  MapPin,
  Droplet,
};
