import {
  AudioLines,
  BookA,
  BookOpen,
  BookOpenText,
  BookUp2,
  Calendar,
  Check,
  ChevronLeft,
  ChevronRight,
  CirclePlus,
  CircleUserRound,
  Command,
  Copy,
  Database,
  Droplet,
  FileText,
  FolderKanban,
  Gauge,
  GraduationCap,
  Headphones,
  History,
  HomeIcon,
  KeyRound,
  LayoutGrid,
  LibraryBig,
  List,
  ListChecks,
  Loader2,
  LogOut,
  NotebookPen,
  PanelLeftClose,
  PanelLeftOpen,
  Pen,
  Slash,
  Speech,
  Star,
  User,
  UserCog,
  UserPlus,
  Users,
} from "lucide-react";

export const Icons = {
  // User related icons
  User: User,
  Users: Users,
  Profile: CircleUserRound,
  UserAdd: UserPlus,
  Settings: UserCog,

  // Session related icons
  Session: KeyRound, // represent session/token

  // Account related icons
  Account: Users, // Grouped icon for users

  //Verification related icons
  Verification: Check,
  // Home Related icons
  Home: HomeIcon,
  Homes: LayoutGrid,
  AddHome: CirclePlus,
  //Water Meter Readings Related Icons
  MeterReading: Droplet,
  MeterReadings: List,
  ReadingsHistory: ListChecks,
  Dashboard: Gauge,

  // General icons
  Learn: BookOpenText,
  Levels: BookUp2,
  Vocabulary: BookA,
  Practice: NotebookPen,
  Reading: BookOpen,
  Listening: Headphones,
  Writing: Pen,
  Speaking: Speech,
  Pronunciation: AudioLines,
  Exams: GraduationCap,
  SignOut: LogOut,
  Books: LibraryBig,
  PanelLeftOpen,
  PanelLeftClose,
  Slash,
  Copy,
  Check,
  Loader: Loader2,
  ChevronRight,
  ChevronLeft,
  Command,
  FileText,
  FolderKanban,
  History,
  Star,
  Add: CirclePlus,
  Calendar: Calendar,
  Database: Database,
};
