name = "dorf-api"
main = "src/index.ts"
compatibility_date = "2024-12-10"
compatibility_flags = ["nodejs_compat_v2"]

[vars]
TURSO_CONNECTION_URL = "TURSO_CONNECTION_URL"
TURSO_AUTH_TOKEN = "TURSO_AUTH_TOKEN"
TRUSTED_ORIGINS = "TRUSTED_ORIGINS"

[env.staging]
name = "dorf-api-staging"
